require:
  - rubocop-rspec

AllCops:
  TargetRubyVersion: 3.1
  NewCops: enable
  SuggestExtensions: false
  Exclude:
    - "bin/**/*"
    - "vendor/**/*"
    - "spec/fixtures/**/*"
    - "spec/vcr_cassettes/**/*"
    - "*.gemspec"

# Layout cops
Layout/LineLength:
  Max: 120
  Exclude:
    - "spec/**/*"

Layout/MultilineMethodCallIndentation:
  EnforcedStyle: indented

Layout/FirstArrayElementIndentation:
  EnforcedStyle: consistent

Layout/FirstHashElementIndentation:
  EnforcedStyle: consistent

# Metrics cops
Metrics/AbcSize:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/BlockLength:
  Exclude:
    - "spec/**/*"
    - "Rakefile"

Metrics/ClassLength:
  Max: 150
  Exclude:
    - "spec/**/*"

Metrics/MethodLength:
  Max: 20
  Exclude:
    - "spec/**/*"

Metrics/ParameterLists:
  Max: 6

# Style cops
Style/Documentation:
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

Style/StringLiteralsInInterpolation:
  EnforcedStyle: double_quotes

Style/FrozenStringLiteralComment:
  Enabled: true
  EnforcedStyle: always

Style/TrailingCommaInArrayLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInHashLiteral:
  EnforcedStyleForMultiline: consistent_comma

Style/TrailingCommaInArguments:
  EnforcedStyleForMultiline: consistent_comma

Style/HashSyntax:
  EnforcedShorthandSyntax: either

# Naming cops
Naming/PredicateName:
  AllowedMethods:
    - is_a?
    - has_key?

Naming/MethodParameterName:
  MinNameLength: 2
  AllowedNames:
    - io
    - id
    - db

# RSpec cops
RSpec/ExampleLength:
  Max: 15

RSpec/MultipleExpectations:
  Max: 5

RSpec/NestedGroups:
  Max: 4

RSpec/DescribeClass:
  Exclude:
    - "spec/integration/**/*"

RSpec/FilePath:
  Enabled: false

RSpec/MultipleMemoizedHelpers:
  Max: 10

RSpec/ContextWording:
  Prefixes:
    - when
    - with
    - without
    - if
    - unless
    - for
    - given
